services:
  # Flask Web Service
  - type: web
    name: trig-verifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
